### ISSUE TITLE
Navigation Menu Expanding on click.

### ISSUE THREAD

**Issue by cesarkohl** [as-one/components__effects#35]
https://www.youtube.com/watch?v=f-yWWcZbVbg&list=PL5e68lK9hEzfe1nPJ2aB5A7jmwgRuTZOm&index=31

**Comment by cesarkohl** [comment]
Great! I like the effect of clicking the X to toggle (open/close) the menu.

**Comment by juliekohl** [comment]
@cesarkohl Good morning,
This effect use jQuery CDN.  ='(
